force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

default_old/objects/Merchandise__c/fields/Value1__c.field-meta.xml
<CustomField>
    <fullName>Value1__c</fullName>
    <label>Value1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/mytest.cls
@isTest
public class mytest {

    Public Static TestMethod void myTest(){
        System.runAs(TestDataUtils.createUser('System Administrator', 'Test')){
            insert new Merchandise__c(Quantity__c = 20, Price__c = 20);
            Merchandise__c m = [Select Id, Quantity__c, Price__c From Merchandise__c LIMIT 1];
            m.value1__c = 20;
        	update m;               
    	}
    }
    
    
    
}